# Generated by Django 5.0.3 on 2024-04-04 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='com_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('mob', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('details', models.TextField(null=True)),
                ('com_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
