# Generated by Django 5.0.3 on 2024-04-04 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_com_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applay_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applay', models.BooleanField(default=False, null=True)),
                ('select', models.BooleanField(default=False, null=True)),
                ('view', models.BooleanField(default=False, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_det', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.add_job')),
            ],
        ),
    ]
