# Generated by Django 5.0.2 on 2024-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_applay_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applay_job',
            name='select',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
