# Generated by Django 5.0.2 on 2024-04-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_applay_job_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applay_job',
            name='select',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
