# Generated by Django 5.0.2 on 2024-04-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_applay_job_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
