# Generated by Django 5.0.2 on 2024-04-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_customuser_is_approved_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_profile',
            name='cv',
            field=models.FileField(null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='add_profile',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
