# Generated by Django 5.0.2 on 2024-04-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_add_profile_cv_add_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edu',
            old_name='edu',
            new_name='edu1',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skil',
            new_name='skil1',
        ),
        migrations.AddField(
            model_name='edu',
            name='edu2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='edu3',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='edu4',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='edu5',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skil2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skil3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skil4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skil5',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
