# Generated by Django 5.0.3 on 2024-04-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_rename_edu_edu_edu1_rename_skil_skill_skil1_edu_edu2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_profile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
