# Generated by Django 5.0.3 on 2024-04-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_add_profile_skills_delete_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_profile',
            name='education',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='add_profile',
            name='skill',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Edu',
        ),
    ]
