# Generated by Django 5.0.3 on 2024-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_add_profile_education_add_profile_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_profile',
            name='image',
            field=models.ImageField(null=True, upload_to='images2/'),
        ),
    ]
