# Generated by Django 5.0.3 on 2024-04-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_com_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job',
            name='education',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='add_job',
            name='skill',
            field=models.CharField(max_length=39, null=True),
        ),
    ]
