# Generated by Django 5.0.3 on 2024-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_add_profile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_profile',
            name='profile',
            field=models.TextField(null=True),
        ),
    ]
