# Generated by Django 5.0.3 on 2024-04-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_add_profile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_profile',
            name='profile',
        ),
    ]
